
//   List CATEGORIES Type
export const GET_CATEGORIES = 'GET_CATEGORIES'
export const GET_CATEGORIES_FULFILLED = "GET_CATEGORIES_FULFILLED"
export const GET_CATEGORIES_REJECTED = "GET_CATEGORIES_REJECTED"


//   List MENU Type
export const GET_LIST_MENU = 'GET_LIST_MENU'
export const GET_LIST_MENU_FULFILLED = "GET_LIST_MENU_FULFILLED"
export const GET_LIST_MENU_REJECTED = "GET_LIST_MENU_REJECTED"


// for transaction reducer
export const SEND_TABLE_NUMBER = 'SEND_TABLE_NUMBER'
export const SEND_TABLE_NUMBER_FULFILLED = "SEND_TABLE_NUMBER_FULFILLED"
export const SEND_TABLE_NUMBER_REJECTED = 'SEND_TABLE_NUMBER_REJECTED'

// for order reducer
export const SEND_ORDERS = 'SEND_ORDER'
export const SEND_ORDERS_FULFILLED = 'SEND_ORDER_FULFILLED'
export const SEND_ORDERS_REJECTED = 'SEND_ORDER_REJECTED'


//   send ITEM MENUS Type
export const SEND_ITEM_MENUS = 'SEND_ITEM_MENUS'
export const SEND_ITEM_MENUS_FULFILLED = "SEND_ITEM_MENUS_FULFILLED"
export const SEND_ITEM_MENUS_REJECTED = "SEND_ITEM_MENUS_REJECTED"

export const GET_ITEM_MENUS = 'GET_ITEM_MENUS'
export const GET_ITEM_MENUS_FULFILLED = "GET_ITEM_MENUS_FULFILLED"
export const GET_ITEM_MENUS_REJECTED = "GET_ITEM_MENUS_REJECTED"


// insert TRANSACTIONS 
export const iNSERT_TRANSACTIONS = 'iNSERT_TRANSACTIONS'
export const iNSERT_TRANSACTIONS_FULFILLED = "iNSERT_TRANSACTIONS_FULFILLED"
export const iNSERT_TRANSACTIONS_REJECTED = "iNSERT_TRANSACTIONS_REJECTED"


